### ISSUE TITLE
ConfigUpdater block server starting

### ISSUE THREAD

**Issue by Cnzw** [RayzsYT/ProAntiTab#5]
My server locate in China, can't access Github due to network problem.

ConfigUpdater cause 4 min delay in server starting, I hope network request timeout can set less, such as 30 sec. Of course, I would appreciate if this feature is configurable or there is another way to solve this problem completely.
```
[15:06:50 INFO]: [ProAntiTab] Enabling ProAntiTab v1.9.0
[15:10:52 WARN]: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
[15:10:52 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:784)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1591)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1589)
[15:10:52 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
[15:10:52 WARN]:        at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:964)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1588)
[15:10:52 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[15:10:52 WARN]:        at ProAntiTab-1.9.0.jar//de.rayzs.pat.utils.ConnectionBuilder.connect(ConnectionBuilder.java:42)
[15:10:52 WARN]:        at ProAntiTab-1.9.0.jar//de.rayzs.pat.utils.configuration.updater.ConfigUpdater.initialize(ConfigUpdater.java:18)
[15:10:52 WARN]:        at ProAntiTab-1.9.0.jar//de.rayzs.pat.plugin.BukkitLoader.onEnable(BukkitLoader.java:56)
[15:10:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[15:10:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:10:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[15:10:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[15:10:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658)
[15:10:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607)
[15:10:52 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742)
[15:10:52 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504)
[15:10:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374)
[15:10:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
[15:10:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:10:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:10:52 WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[15:10:52 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[15:10:52 WARN]:        ... 27 more
[15:10:52 INFO]: [ProAntiTab] Successfully hooked into PlaceholderAPI!
[15:10:52 INFO]: [PlaceholderAPI] Successfully registered internal expansion: pat [1.9.0]
[15:10:53 INFO]: [ProAntiTab] Successfully hooked into LuckPerms for easier usage.
[15:10:53 INFO]: [ProAntiTab] Successfully hooked into ViaVersion for easier usage.
```

**Comment by RayzsYT** [comment]
Yea sure.

I can add an option for ya to disable the AutoUpdater entirely + an actual timeout. 

Sorry for that. Stupid from me not to include it in the first place. 😅

**Comment by RayzsYT** [comment]
K. First test version with this feature included is being tested. I'll let you know when I have a jar for ya to use. ^^

**Comment by RayzsYT** [comment]
Okay. I just uploaded an experimental version of PAT that includes the requested feature and some other changes as well.
Unfortunately, it would require you to delete your current config.yml file.

https://github.com/RayzsYT/ProAntiTab/releases/tag/v1.9.1-Experimental

Please lemme know if it works. ^^

**Comment by Cnzw** [comment]
I test v1.9.1-Experimental in Purpur and Bungeecord. It works fine, didn't cause any timeout or block server starting problems.

Thanks for your work on this problem! 👍

**Comment by RayzsYT** [comment]
Glad to hear! ^^
